version: '3.8'

services:
  db-1:
    image: postgres:15
    container_name: db-1
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: gerenciamento_de_clientes
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin-1:
    image: dpage/pgadmin4
    container_name: pgadmin-1
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: user@gerenciamento-equipes.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db-1

volumes:
  postgres_data: