
### Criar um novo usuário
POST http://localhost:8080/usuario
Content-Type: application/json

{
  "nomeCompleto": "Carlos Eduardo Santos Silva",
  "email": "carlos.silva@empresa.com",
  "senha": "E?a655hMGtptrS1ID$FS4@",
  "nivelAcesso": "ADMIN",
  "cargo": "DESENVOLVEDOR",
  "telefone": "(70)3800-3268"
}


### Login de usuário (gera token JWT)
POST http://localhost:8080/usuario/login
Content-Type: application/json

{
  "email": "carlos.silva@empresa.com",
  "senha": "E?a655hMGtptrS1ID$FS4@"
}

### Pesquisa de usuários por nome/email
GET http://localhost:8080/usuario/usuarios/pesquisa?nome=Gustavo&email=
Authorization: Bearer {{token}}

### Filtrar usuários por cargo/status/nivel
GET http://localhost:8080/usuario/usuarios/filtros?cargo=ADMIN&status=ATIVO&nivel=GERENTE
Authorization: Bearer {{token}}

### Atualizar dados de um usuário
PATCH http://localhost:8080/usuario
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nomeCompleto": "Carlos Eduardo Santos Silva",
  "email": "carlos.silva@empresa.com",
  "senha": "E?a655hMGtptrS1ID$FS4@",
  "nivelAcesso": "ADMIN",
  "cargo": "DESENVOLVEDOR",
  "telefone": "(07)7683-6649",
  "statusUser": "ATIVO"
}

### Inativar usuário (DELETE por ID)
DELETE http://localhost:8080/usuario/{{email}}
Authorization: Bearer {{token}}