
### Criar um novo usuário
POST http://localhost:8080/usuario
Content-Type: application/json
[
   {
    "nomeCompleto": "Ana Maria Oliveira Costa",
    "email": "ana.costa@empresa.com",
    "senha": "KKkkkjjjjj33@",
    "nivelAcesso": "ADMIN",
    "cargo": "DESENVOLVEDOR",
    "telefone": "(21)99876-5432"
  },
  {
    "nomeCompleto": "Pedro Henrique Almeida",
    "email": "pedro.almeida@empresa.com",
    "senha": "Yw7$hN9pM4kL#vB2",
    "nivelAcesso": "MEMBRO",
    "cargo": "GERENTE",
    "telefone": "(11)97654-3210"
  },
  {
    "nomeCompleto": "Mariana Santos Lima",
    "email": "mariana.lima@empresa.com",
    "senha": "Qz5#jX8nV3mK$pL7",
    "nivelAcesso": "MEMBRO",
    "cargo": "DESENVOLVEDOR",
    "telefone": "(31)98765-4321"
  },
  {
    "nomeCompleto": "Lucas Fernandes Souza",
    "email": "lucas.souza@empresa.com",
    "senha": "Ht6@wR4cB9dM$nE2",
    "nivelAcesso": "MEMBRO",
    "cargo": "GERENTE",
    "telefone": "(47)99632-8521"
  }
]

### Login de usuário (gera token JWT)
POST http://localhost:8080/usuario/login
Content-Type: application/json

{
  "email": "carlos.silva@empresa.com",
  "senha": "E?a655hMGtptrS1ID$FS4@"
}

### Pesquisa de usuários por nome/email
GET http://localhost:8080/usuario/usuarios/pesquisa?nome=Gustavo&email=
Authorization: Bearer {{token}}

### Filtrar usuários por cargo/status/nivel
GET http://localhost:8080/usuario/usuarios/filtros?cargo=ADMIN&status=ATIVO&nivel=GERENTE
Authorization: Bearer {{token}}

### Atualizar dados de um usuário
PATCH http://localhost:8080/usuario
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nomeCompleto": "Carlos Eduardo Santos Silva",
  "email": "carlos.silva@empresa.com",
  "senha": "E?a655hMGtptrS1ID$FS4@",
  "nivelAcesso": "ADMIN",
  "cargo": "DESENVOLVEDOR",
  "telefone": "(07)7683-6649",
  "statusUser": "ATIVO"
}

### Inativar usuário (DELETE por ID)
DELETE http://localhost:8080/usuario/{{email}}
Authorization: Bearer {{token}}

### Criar Tarefa
POST http://localhost:8080/api/tarefas
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "titulo": "Criar site institucional",
  "descricao": "Landing page simples para divulgação",
  "status": "A_FAZER",
  "prioridade": "BAIXA",
  "dataEntrega": "2025-12-29T21:02:23.058Z",
  "projeto": "Portal Corporativo",
  "tags": "#frontend #landingpage",
  "responsavelId": "9ab1524c-de80-4cfa-a230-276cb7fe2f92"

}
