spring:
  profiles:
    active: Prod

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://db:5432/db_clientes
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:db_cliente
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE



jackson:
  mapper:
    accept-case-insensitive-enums: true
