spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
      url: jdbc:postgresql://localhost:5432/gerenciamento_de_clientes
      username: admin
      password: admin123
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:db_cliente
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


